include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore 
    avoid_positional_boolean_parameters: ignore
    prefer_if_elements_to_conditional_expressions: ignore
