name: ui_components
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  adaptive_dialog: ^2.2.1+2
  another_flushbar: ^1.12.30
  cloud_firestore: ^5.5.0
  country_phone_validator: ^1.0.1
  dropdown_search: ^6.0.1
  easy_debounce: ^2.0.3
  email_validator: ^3.0.0
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  kmbal_ionicons: ^1.0.0
  permission_handler: ^11.3.1
  popover: ^0.3.1
  skeletonizer: ^1.4.2
  string_extensions: ^0.7.3
  styled_text: ^8.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
